### ISSUE TITLE
Error in running test

### ISSUE THREAD

**Issue by MiladAlshomary** [leifos/simiir#3]
Hello,

I downloaded the framework and setup all required libraries. Trying to run the provided sample simulations:
python run_simiir.py ../example_sims/trec_bm25_simulation.xml
Throws an at the end of the simulation. The output of the command is:

`SIMULATION 'example_bm25_sim-367-smartuser'
  Simulation Configuration:
    Topic: 367
    Search Interface: WhooshSearchInterface
        whoosh_index_dir: ../example_data/index
        implicit_or: True
        model: 1

  User Configuration (smartuser):
    Query Generator: SmarterQueryGenerator
        stopword_file: ../example_data/terms/stopwords.txt
    Snippet Classifier: StochasticInformedTrecTextClassifier
        qrel_file: ../example_data/qrels/trec2005.qrels.all
        rprob: 0.75
        nprob: 0.35
        data_handler: 0
    Document Classifier: StochasticInformedTrecTextClassifier
        qrel_file: ../example_data/qrels/trec2005.qrels.all
        rprob: 0.85
        nprob: 0.25
        data_handler: 0
    Stopping Decision Maker: SequentialNonrelDecisionMakerSkip
        nonrelevant_threshold: 3
    SERP Impression: SimpleSERPImpression
        qrel_file: ../example_data/qrels/trec2005.qrels.all
    Logger: FixedCostLogger
        time_limit: 600
        query_cost: 10
        document_cost: 20
        snippet_cost: 3
        serp_results_cost: 5
        mark_document_cost: 3
    Search Context: SearchContext
        relevance_revision: 1

  Results Summary:
    Number of Queries Issued: 4
    Number of Snippets Examined: 36
    Number of Documents Examined: 20
    Number of Documents Marked Relevant: 13
    Number of Attractive SERPs Examined: 4
    Number of Unattractive SERPs Examined: 0

Traceback (most recent call last):
  File "run_simiir.py", line 50, in <module>
    main(sys.argv[1])
  File "run_simiir.py", line 19, in main
    for configuration in config_reader:
  File "/home/malshomary/Dev/wstud-user-simulation/simiir/simiir/config_readers/simulation_config_reader.py", line 59, in next
    bg = SimulationComponentGenerator(self._config_dict['@id'], configuration_set)
  File "/home/malshomary/Dev/wstud-user-simulation/simiir/simiir/config_readers/component_generators/simulation_generator.py", line 33, in __init__
    self.user = UserConfigReader(user_config_file).get_component_generator(self)
  File "/home/malshomary/Dev/wstud-user-simulation/simiir/simiir/config_readers/user_config_reader.py", line 16, in get_component_generator
    return UserComponentGenerator(simulation_components, self._config_dict)
  File "/home/malshomary/Dev/wstud-user-simulation/simiir/simiir/config_readers/component_generators/user_generator.py", line 58, in __init__
    components=[('search_context', self.search_context)])
  File "/home/malshomary/Dev/wstud-user-simulation/simiir/simiir/config_readers/component_generators/base_generator.py", line 66, in _get_object_reference
    reference = available_class[1](**kwargs)
TypeError: __init__() takes at least 3 arguments (2 given)`

However, I still see in the output folder the simulation results but still don't know if this error effect the output in anyway.

Thanks in advance for your help!

**Comment by maxwelld90** [comment]
Hi @MiladAlshomary,
Thanks for getting in touch. Appreciate it.
I found a mistake in the configuration files for the examples -- we added a new component, and I hadn't pushed changes to the config files. I have made these changes now, so if you do a git pull and try again, everything should run without error...

Please let me know how you get on!
Cheers,
David

**Comment by MiladAlshomary** [comment]
I pulled your updates and now things are working properly.

Thanks!
